[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
healthcheckPath = "/"  # Chỉ định đường dẫn kiểm tra sức khỏe
healthcheckTimeout = 100  # Đặt thời gian chờ tối đa (tính bằng giây)
restartPolicyType = "never"