[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
healthcheckPath = "https://zalolite-account-server-production.up.railway.app"  # Chỉ định đường dẫn kiểm tra sức khỏe
healthcheckTimeout = 300  # Đặt thời gian chờ tối đa (tính bằng giây)
restartPolicyType = "never"