[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
healthcheckTimeout = 300  # Đặt thời gian chờ tối đa (tính bằng giây)
restartPolicyType = "never"